[build]
  # Build command for Flutter web
  command = "git clone https://github.com/flutter/flutter.git --depth 1 --branch $FLUTTER_VERSION && export PATH=\"$PATH:`pwd`/flutter/bin\" && flutter doctor && flutter build web --release --dart-define=SUPABASE_URL=$SUPABASE_URL --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY --dart-define=WEBHOOK_URL=$WEBHOOK_URL --dart-define=PRODUCTION=true"
  
  # Output directory after build
  publish = "build/web"

[build.environment]
  # Flutter version to use
  FLUTTER_VERSION = "3.22.2"

# Redirect rules for Flutter web routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"